# Generated by Django 5.0.2 on 2024-02-29 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="nombre")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
            ],
            options={
                "verbose_name": "proyecto",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=256,
                        primary_key=True,
                        serialize=False,
                        verbose_name="nombre",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="main.project",
                        verbose_name="proyecto",
                    ),
                ),
            ],
            options={
                "verbose_name": "dominio",
                "ordering": ["-created"],
            },
        ),
    ]
