# Generated by Django 5.0.4 on 2024-05-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="urls",
            field=models.TextField(blank=True, verbose_name="URLs"),
        ),
    ]
