# Generated by Django 5.0.4 on 2024-05-25 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_domain_urls"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="domain",
            name="urls",
        ),
        migrations.CreateModel(
            name="URL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(verbose_name="URL")),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="urls",
                        to="main.domain",
                        verbose_name="dominio",
                    ),
                ),
            ],
        ),
    ]
