# Generated by Django 5.0.4 on 2024-05-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_delete_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="urls",
            field=models.TextField(
                blank=True,
                help_text="Enter URLs separated by commas.",
                verbose_name="URLs",
            ),
        ),
    ]
