# Generated by Django 5.0.4 on 2024-05-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_domain_urls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="urls",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Enter a list of URLs.",
                verbose_name="URLs",
            ),
        ),
    ]
