# Generated by Django 5.0.4 on 2024-05-31 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_domain_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="token",
            field=models.CharField(
                editable=False, max_length=256, verbose_name="Token"
            ),
        ),
    ]
