# Generated by Django 5.0.4 on 2024-05-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_alter_domain_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="token",
            field=models.CharField(max_length=256, verbose_name="Token"),
        ),
    ]
