# Generated by Django 5.0.4 on 2024-06-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_alter_domain_federation_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="canary_token",
            field=models.CharField(
                blank=True,
                help_text="Canary Token para la protección anti-clonado del dominio",
                max_length=256,
                verbose_name="Canary Token",
            ),
        ),
    ]
