# Generated by Django 5.0.4 on 2024-06-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_domain_canary_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="canary_token",
            field=models.URLField(
                blank=True,
                help_text="URL de los Canary Token para la protección anti-clonado del dominio",
                max_length=256,
                verbose_name="Canary Token",
            ),
        ),
    ]
