# Generated by Django 5.0.4 on 2024-06-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_alter_domain_canary_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="urls",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Introduce las URLs del dominio en formato JSON. Ejemplo: ["https://example.com", "https://anotherexample.com"]',
                verbose_name="URLs",
            ),
        ),
    ]
