# Generated by Django 5.0.4 on 2024-06-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_alter_domain_urls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="token",
            field=models.CharField(blank=True, max_length=256, verbose_name="Token"),
        ),
    ]
