# Generated by Django 5.0.4 on 2024-05-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proactive", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="similardomain",
            name="total_weight",
            field=models.FloatField(default=0.0, verbose_name="Peso total"),
        ),
        migrations.AlterField(
            model_name="similardomain",
            name="bad_links",
            field=models.JSONField(default=list, verbose_name="Enlaces enganosos"),
        ),
    ]
