# Generated by Django 5.0.4 on 2024-06-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proactive", "0002_similardomain_total_weight_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="similardomain",
            name="tld_country",
            field=models.CharField(
                blank=True,
                max_length=32,
                null=True,
                verbose_name="Pais asociado al TLD",
            ),
        ),
    ]
