# Generated by Django 5.0.4 on 2024-06-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proactive", "0003_alter_similardomain_tld_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="similardomain",
            name="visual_similarity",
            field=models.JSONField(blank=True, verbose_name="Similitud visual"),
        ),
    ]
