# Generated by Django 5.0.4 on 2024-06-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proactive", "0004_alter_similardomain_visual_similarity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="similardomain",
            name="visual_similarity",
            field=models.JSONField(null=True, verbose_name="Similitud visual"),
        ),
    ]
