# Generated by Django 5.0.4 on 2024-06-04 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0016_alter_domain_urls"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "host",
                    models.CharField(
                        help_text="Dominio malicioso detectado",
                        max_length=255,
                        verbose_name="Dominio malicioso detectado",
                    ),
                ),
                (
                    "referrer",
                    models.CharField(
                        help_text="Referrer del dominio malicioso",
                        max_length=255,
                        verbose_name="Referrer del dominio malicioso",
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        help_text="IP en la que se aloja el dominio malicioso",
                        verbose_name="IP en la que se aloja el dominio malicioso",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha de detección",
                        verbose_name="Fecha de detección",
                    ),
                ),
                (
                    "revisado",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si el alerta ha sido revisada por un administrador",
                        verbose_name="Revisado",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        help_text="Dominio original suplantado",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.domain",
                        verbose_name="Dominio original suplantado",
                    ),
                ),
            ],
        ),
    ]
